blank_issues_enabled: false
contact_links:
  - name: AUR Package Page
    url: https://aur.archlinux.org/packages/
    about: Visit the AUR package page for community discussions
  - name: General Discussion
    url: https://github.com/xifan-wd/aur-auto/discussions
    about: Ask questions and discuss ideas with the community
