#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
META_FILE="${ROOT_DIR}/metadata/maintainers.env"
OUTPUT_EN="${ROOT_DIR}/README.md"
OUTPUT_ZH="${ROOT_DIR}/README.zh.md"

if [[ ! -f "${META_FILE}" ]]; then
	echo "Metadata file missing: ${META_FILE}" >&2
	exit 1
fi

# shellcheck disable=SC1090
source "${META_FILE}"

: "${AUR_USER:?Missing AUR_USER in ${META_FILE}}"
: "${AUR_EMAIL:?Missing AUR_EMAIL in ${META_FILE}}"
: "${GITHUB_SLUG:=}"

BUILD_WORKFLOW="build-and-publish.yml"

# Discover and sort packages
declare -a pkg_dirs=()
while IFS= read -r -d '' dir; do
	pkg_dirs+=("${dir}")
done < <(find "${ROOT_DIR}/pkgs" -mindepth 1 -maxdepth 1 -type d -print0)

declare -A dir_map=()
for dir in "${pkg_dirs[@]}"; do
	base="$(basename "${dir}")"
	dir_map["${base}"]="${dir}"
done

mapfile -t sorted_names < <(printf '%s\n' "${!dir_map[@]}" | sort)

# Build package table rows
table=""
for name in "${sorted_names[@]}"; do
	dir="${dir_map[${name}]}"
	pkgbuild="${dir}/PKGBUILD"
	if [[ ! -f "${pkgbuild}" ]]; then
		continue
	fi

	pkg_info="$(bash -c "source '${pkgbuild}'; printf '%s|%s|%s|%s' \"\${pkgname}\" \"\${pkgver}\" \"\${pkgdesc}\" \"\${_pkgname:-}\"")"
	pkg_name="${pkg_info%%|*}"
	rest="${pkg_info#*|}"
	pkg_version="${rest%%|*}"
	rest="${rest#*|}"
	pkg_desc="${rest%%|*}"
	upstream_name="${rest#*|}"

	if [[ -z "${upstream_name}" ]]; then
		upstream_name="${pkg_name}"
	fi

	pkg_desc="${pkg_desc//$'\n'/ }"
	pkg_desc="${pkg_desc//|/\\|}"
	upstream_name="${upstream_name//|/\\|}"

	build_status="N/A"
	if [[ -n "${GITHUB_SLUG}" ]]; then
		badge_url="https://img.shields.io/github/actions/workflow/status/${GITHUB_SLUG}/${BUILD_WORKFLOW}?branch=main&logo=github&label=build"
		link_url="https://github.com/${GITHUB_SLUG}/actions/workflows/${BUILD_WORKFLOW}"
		build_status="[![Build Status](${badge_url})](${link_url})"
	fi

	table+="| \`${pkg_name}\` | ${pkg_desc} | \`${upstream_name}\` | ${pkg_version} | ${build_status} |"$'\n'
done

# Remove trailing newline
table="${table%$'\n'}"

# Generate English README
cat > "${OUTPUT_EN}" << EOF
<!-- This file is auto-generated by scripts/build-readme.sh. Do not edit manually. -->

# aur-auto

[![AUR Maintainer](https://img.shields.io/badge/AUR-${AUR_USER}-1793D1?logo=arch-linux&logoColor=white)](https://aur.archlinux.org/packages?SeB=m&K=${AUR_USER})

Automation toolkit for maintaining Arch User Repository packages with GitHub Actions.

## Overview
- Detect upstream releases per package by calling dedicated hooks in \`pkgs/<pkgname>/upstream.sh\`.
- Regenerate PKGBUILD metadata, build packages in clean chroots, and publish to AUR.

## Maintainers
- ${AUR_USER} \`<${AUR_EMAIL}>\`

## Packages
| Package | Description | Upstream | Version | Build Status |
| --- | --- | --- | --- | --- |
${table}

Regenerate this README after documentation or metadata changes with \`scripts/build-readme.sh\`.
EOF

# Generate Chinese README
cat > "${OUTPUT_ZH}" << EOF
<!-- 该文件由 scripts/build-readme.sh 自动生成，请勿手动编辑。 -->

# aur-auto

[![AUR 维护者](https://img.shields.io/badge/AUR-${AUR_USER}-1793D1?logo=arch-linux&logoColor=white)](https://aur.archlinux.org/packages?SeB=m&K=${AUR_USER})

使用 GitHub Actions 自动维护 Arch User Repository 软件包的工具集。

## 项目概览
- 每个包通过 \`pkgs/<pkgname>/upstream.sh\` 钩子检测上游新版本。
- 自动更新 PKGBUILD 元数据，在 clean chroot 中构建并推送至 AUR。

## 维护者
- ${AUR_USER} \`<${AUR_EMAIL}>\`

## 软件包
| Package | Description | Upstream | Version | Build Status |
| --- | --- | --- | --- | --- |
${table}

文档或元数据更新后，请运行 \`scripts/build-readme.sh\` 重新生成 README。
EOF

echo "README.md and README.zh.md regenerated."
